web/urls.py
from django.contrib import admin
from django.urls import path
import sys
sys.path.append('./web')
import views
import control

app_name = 'zeroOut'
urlpatterns = [
    path('', views.index, name='index'),
    path('login', control.login, name='login'),
    path('check_register', control.check_register, name='check_register'),
    path('register', views.register, name='register'),
    path('about', views.about, name='about'),
    path('get_home', control.get_home, name='get_home'),
    path('get_my_follow_user',views.get_my_follow_user, name='get_my_follow_user'),
    path('delete_follow_user',views.delete_follow_user, name='delete_follow_user'),
    path('get_my_fan',views.get_my_fan, name='get_my_fan'),
    path('delete_fan',views.delete_fan, name='delete_fan'),

    path('send_weibo', control.send_weibo, name="send_weibo"),
    path('get_my_weibo', views.get_my_weibo, name="get_my_weibo"),
    path('get_my_follow_weibo', views.get_my_follow_weibo, name="get_my_follow_weibo"),
    path('get_my_user_home',control.get_my_user_home, name='get_my_user_home'),
    path('get_other_user_home',control.get_other_user_home, name='get_other_user_home'),
    path('display_profile',control.edit_profile, name='display_profile'),
    path('update_profile',control.update_profile, name='update_profile'),
    path('change_passwd',control.change_passwd, name='change_passwd'),
    path('enter_change_passwd',views.enter_change_passwd, name='enter_change_passwd'),
    path('explore', control.random_choose_user, name='explore'),
    path('follow_in_explore',control.follow_in_explore, name='follow_in_explore')
]

zeroOutSocial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('zeroOut/', include('web.urls')),
    path('admin/', admin.site.urls),
]

web/models.py
from django.db import models

# Create your models here.

web/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django.template import RequestContext
from django.shortcuts import render_to_response
import sys
sys.path.append('./web/model')
sys.path.append('./web')
from GstoreConnector import GstoreConnector
from weiBo import Weibo
from followRelation import User

gstore = GstoreConnector("localhost", 9000, "root", "123456")
weibo = Weibo(gstore)
user = User(gstore)

def index(request):
    response = render(request, 'login.html')
    return response

def register(request):
    response = render(request, 'register.html')
    return response

def about(request):
    response = render(request, 'about.html')
    return response

def get_my_follow_user(request):
    return user.get_my_follow_user(request)

def delete_follow_user(request):
    uid = request.POST['followuid']
    return user.delete_follow_user(request, uid)

def get_my_fan(request):
    return user.get_my_fan(request)

def delete_fan(request):
    uid = request.POST['fanuid']
    return user.delete_fan(request,uid)

def get_my_weibo(request):
    return weibo.get_my_weibo(request)

def get_my_follow_weibo(request):
    return weibo.get_my_follow_weibo(request)

def enter_change_passwd(request):
	return render(request, 'changePwd.html')

web/templates/about.html
<!DOCTYPE html>

<html>
<head>
	<meta charset="UTF-8">
	<title>关于ZeroOut</title>
	<link rel="stylesheet" href="../static/css/style.css" type="text/css">
</head>
<body>
	<div class="page">
		<div class="header">
			<div>
				<a href="/zeroOut/" id="logo"><img src="../static/images/logo.gif" alt="logo"></a>
				<ul>
					<li>
						<a href="/zeroOut/">登录</a>
					</li>
					<li>
						<a href="/zeroOut/register">注册</a>
					</li>
					<li>
						<li class="selected">
						<a href="/zeroOut/about">关于</a>
					</li>
				</ul>
			</div>
		</div>
			<div>
				<ul class="blog">
					<li>
						<a href="/zeroOut/about"><img src="../static/images/glove.png" alt=""></a>
						<h3>ZeroOut是基于gStore图数据库系统的社交网络</h3>
						<p>ZeroOut Social is a social network website based on gStore System.</p>
					</li>
					<li>
						<a href="/zeroOut/about"><img src="../static/images/baseball.png" alt=""></a>
						<h3>ZeroOut是基于gStore图数据库系统的社交网络</h3>
						<p>You can post microblog after you log in.</p>
					</li>
					<li>
						<a href="/zeroOut/about"><img src="../static/images/bat.png" alt=""></a>
						<h3>ZeroOut是基于gStore图数据库系统的社交网络</h3>
						<p>You can follow other people to find out what they are talking about and feeling.</p>
					</li>
				</ul>
			</div>
		</div>
		<div class="footer">
			<div>
				<ul>
					<li>
						<a href="/zeroOut/">登录</a>
					</li>
					<li>
						<a href="/zeroOut/register">注册</a>
					</li>
					<li>
						<a href="/zeroOut/about">关于</a>
					</li>
				</ul>
				<p>ZeroOut Social is a social network website based on gStore System. You can post microblog after you log in. You can also follow other people to find out what they are talking about and feeling.</p>
				<div class="connect">
					<a href="#" id="sina">weibo</a>
					<a href="#" id="facebook">facebook</a>
					<a href="#" id="twitter">twitter</a>
				</div>
				<p class="footnote">&#169; Copyright &#169; 2019. ZeroOut Group. All rights reserved</p>
				<p class="footnote"> SNS Website Using gStore System, Peking University</p>
			</div>
		</div>
</body>
</html>

web/templates/changePwd.html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>帐号设置</title>
	<link rel="stylesheet" href="../static/css/style.css" type="text/css">
<script>
<!--
	function check_info(form)
	{
		if(form.old_pwd.value=="")
		{
			alert("请填写您现在的密码!");
			form.old_pwd.focus();
			return false;
		}
		if(form.old_pwd.value.length<3 || form.old_pwd.value.length>30)
		{
			alert("密码的长度必须在3-20之间！");
			form.old_pwd.focus();
			return false;
		}
		if(form.new_pwd.value=="")
		{
			alert("请填写新的密码");
			form.new_pwd.focus();
			return false;
		}
		if(form.old_pwd.value == form.new_pwd.value)
		{
			alert("密码未做修改");
			form.new_pwd.focus();
			return false;
		}
	}
-->
</script>
<body>
<div class="page">
		<div class="header">
			<div>
				<a href="/zeroOut/" id="logo"><img src="../static/images/logo.gif" alt="logo"></a>
				<ul>
					<li>
						<a href="/zeroOut/get_home">首页</a>
					</li>
					<li>
						<a href="/zeroOut/get_my_user_home">个人主页</a>
					</li>
					<li>
						<a href="/zeroOut/get_my_follow_user">关注</a>
					</li>
					<li>
						<a href="/zeroOut/get_my_fan">粉丝</a>
					</li>
					<li>
						<a href="/zeroOut/display_profile">个人资料</a>
					</li>
					<li class="selected">
						<a href="/zeroOut/enter_change_passwd">我的帐号</a>
					</li>
					<li>
						<a href="/zeroOut/explore">随便看看</a>
					</li>
					<li>
						<a href="/zeroOut/">登出</a>
					</li>
				</ul>
			</div>
		</div>
		<div class="body">
			<div>
				<div>
					<ul class="blog">		
						<form action="{% url 'zeroOut:change_passwd' %}" method="post" onSubmit="return check_info(this);">
						<center>
						<table width="520" border="0" bordercolor="#99CCFF" cellpadding="0"
							cellspacing="0" style="border-collapse: collapse">
							<!--DWLayoutTable-->
							<tr>
								<td height="40" colspan="2" align="center"><h3>修改帐号密码</h3></td>
							</tr>
							<tr height="40"></tr>
							<tr>
								<td width="24%" height="40" align="right">当前密码：&nbsp;<font color="red">*</font></td>
								<td width="76%" height="40" align="left">&nbsp;&nbsp;&nbsp;<input
									type="password" name="origin_passwd" /> （数字或者是字符[<font color="red">3-30</font>]）
							</tr>
							<tr>
								<td height="40" align="right">新的密码：&nbsp;<font color="red">*</font></td>
								<td height="40" align="left">&nbsp;&nbsp;&nbsp;<input
									type="password" name="new_passwd" /> </td>
							</tr>
							<tr>
								<td height="40" colspan="2" align="center"><input type="submit"
									value=" 提交 " /> &nbsp;<input type="button"
									onClick="history.go(-1);" value=" 返回 " /></td>
							</tr>
						</table>
						</center>
						</form>
				</div>
			</div>
		</div>
		
		<div class="footer">
			<div>
				<ul>
					<li>
						<a href="/zeroOut/">登录</a>
					</li>
					<li>
						<a href="/zeroOut/register">注册</a>
					</li>
					<li>
						<a href="/zeroOut/about">关于</a>
					</li>
				</ul>
				
				<div class="connect">
					<a href="#" id="sina">weibo</a>
					<a href="#" id="facebook">facebook</a>
					<a href="#" id="twitter">twitter</a>
				</div>
				<p class="footnote">&#169; Copyright &#169; 2019. ZeroOut Group. All rights reserved</p>
				<p class="footnote"> SNS Website Using gStore System, Peking University</p>
			</div>
		</div>
	</div>
</body>
</html>



web/templates/explore.html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>随便看看</title>
	<link rel="stylesheet" href="../static/css/style.css" type="text/css">
<script>
<!--
function change(input)
{	
	if(input.value=="删除好友")
		input.value="加为好友";
	else
		input.value="加为好友";
	return true;

}
-->
</script>
</head>
<body>
<div class="page">
		<div class="header">
			<div>
				<a href="/zeroOut/" id="logo"><img src="../static/images/logo.gif" alt="logo"></a>
				<ul>
					<li>
						<a href="/zeroOut/get_home">首页</a>
					</li>
					<li>
						<a href="/zeroOut/get_my_user_home">个人主页</a>
					</li>
					<li> 
						<a href="/zeroOut/get_my_follow_user">关注</a>
					</li>
					<li >
						<a href="/zeroOut/get_my_fan">粉丝</a>
					</li>
					<li>
						<a href="/zeroOut/display_profile">个人资料</a>
					</li>
					<li>
						<a href="/zeroOut/enter_change_passwd">我的帐号</a>
					</li>
					<li class="selected">
						<a href="/zeroOut/explore">随便看看</a>
					</li>
					<li>
						<a href="/zeroOut/">登出</a>
					</li>
				</ul>
			</div>
		</div>
		<div class="body">
			<div>
				<div>
				<ul class="blog">
				
										
				<table width="80%" border="0">
				<tr>
					<td>
					<p>&nbsp;&nbsp;你可能感兴趣：</p>
					{%if users%}
					<table id="block" style="margin-top:25px">
                    <tr>
                    <th> Name </th>
                    <th> Follow </th>
                    <th> Homepage </th>
                    </tr>
					{%for user in users%}
					    <tr>
						<td>{{ user.name }}</td>
                        <td>
							<form name="FollowForm" action = "{% url 'zeroOut:follow_in_explore' %}" method="post">
                            {% csrf_token %}
							<p>
								<input type="hidden" name="uid" value={{user.uid}}>
								&nbsp;&nbsp;&nbsp;&nbsp;
								<input type="submit" name="FollowUser" value="添加关注"/>
							</p>
						    </form>
                        </td>
                    <td>
						<form name="FollowersHomepageForm" action="{% url 'zeroOut:get_other_user_home' %}" method="post">
                        {% csrf_token %}
						<p>
						<input type="hidden" name="uid" value={{user.uid}}> 
						&nbsp;&nbsp;&nbsp;&nbsp;
                        <input type="submit" name="homepage" value="ta的主页"/>
						</p>
						</form>
                    </td>
					    </tr>
                    {% endfor %}
                    </table>
                    {% else %}
                    <p>No followers are available.</p>
                    {% endif %}
					</td>
					</tr>
					</table>
					</ul>
				</div>
			</div>
		</div>
		
		<div class="footer">
			<div>
				<ul>
					<li>
						<a href="/zeroOut/">登录</a>
					</li>
					<li>
						<a href="/zeroOut/register">注册</a>
					</li>
					<li>
						<a href="/zeroOut/about">关于</a>
					</li>
				</ul>
				
				<div class="connect">
					<a href="#" id="sina">weibo</a>
					<a href="#" id="facebook">facebook</a>
					<a href="#" id="twitter">twitter</a>
				</div>
				<p class="footnote">&#169; Copyright &#169; 2019. ZeroOut Group. All rights reserved</p>
				<p class="footnote"> SNS Website Using gStore System, Peking University</p>
			</div>
		</div>
	</div>
</body>
</html>

web/templates/fans.html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>我的粉丝</title>
	<link rel="stylesheet" href="../static/css/style.css" type="text/css">
<script>
<!--
function change(input)
{	
	if(input.value=="删除好友")
		input.value="加为好友";
	else
		input.value="加为好友";
	return true;

}
-->
</script>
</head>
<body>
<div class="page">
		<div class="header">
			<div>
				<a href="/zeroOut/" id="logo"><img src="../static/images/logo.gif" alt="logo"></a>
				<ul>
					<li>

						<a href="/zeroOut/get_home">首页</a>
					</li>
					<li>
						<a href="/zeroOut/get_my_user_home">个人主页</a>
					</li>
					<li>
						<a href="/zeroOut/get_my_follow_user">关注</a>
					</li>
					<li class="selected">
						<a href="/zeroOut/get_my_fan">粉丝</a>
					</li>
					<li>
						<a href="/zeroOut/display_profile">个人资料</a>
					</li>
					<li>
						<a href="/zeroOut/enter_change_passwd">我的帐号</a>
					</li>
					<li>
						<a href="/zeroOut/explore">随便看看</a>
					</li>
					<li>
						<a href="/zeroOut/">登出</a>
					</li>
				</ul>
			</div>
		</div>
		<div class="body">
			<div>
				<div>
				<ul class="blog">							
				<table width="80%" border="0">
				<tr>
					<td>
					<p>&nbsp;&nbsp;我的粉丝：</p>
                    {% if fans %}
                    <table id="blocks" style="margin-top:25px">
                    <tr>
                    <th> Name </th>
                    <th> Delete </th>
                    <th> HomePage </th>
                    </tr>
                    {% for fan in fans %}
                    <tr>
                    <td>{{fan.name}}</td>
                    <td>
						<form name="removeFansForm" action="{% url 'zeroOut:delete_fan' %}" method="post">
                        {% csrf_token %}
						<p>
						<input type="hidden" name="fanuid" value={{fan.uid}}> 
						&nbsp;&nbsp;&nbsp;&nbsp;
                        <input type="submit" name="removeFans" value="移除粉丝"/>
						</p>
						</form>
                    </td>
                    <td>
						<form name="FansHomepageForm" action="{% url 'zeroOut:get_other_user_home' %}" method="post">
                        {% csrf_token %}
						<p>
						<input type="hidden" name="uid" value={{fan.uid}}> 
						&nbsp;&nbsp;&nbsp;&nbsp;
                        <input type="submit" name="homepage" value="ta的主页"/>
						</p>
						</form>
                    </td>
                    </tr>
                    {% endfor %}
                    </table>
                    {% else %}
                    <p>No fans are available.</p>
                    {% endif %}
					</td>
					</tr>
					</table>
					</ul>
				</div>
			</div>
		</div>
		
		<div class="footer">
			<div>
				<ul>
					<li>
						<a href="/zeroOut/">登录</a>
					</li>
					<li>
						<a href="/zeroOut/register">注册</a>
					</li>
					<li>
						<a href="/zeroOut/about">关于</a>
					</li>
				</ul>
				
				<div class="connect">
					<a href="#" id="sina">weibo</a>
					<a href="#" id="facebook">facebook</a>
					<a href="#" id="twitter">twitter</a>
				</div>
				<p class="footnote">&#169; Copyright &#169; 2019. ZeroOut Group. All rights reserved</p>
				<p class="footnote"> SNS Website Using gStore System, Peking University</p>
			</div>
		</div>
	</div>
</body>
</html>

web/templates/follow.html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>我的关注</title>
	<link rel="stylesheet" href="../static/css/style.css" type="text/css">
<script>
<!--
function change(input)
{	
	if(input.value=="删除好友")
		input.value="加为好友";
	else
		input.value="加为好友";
	return true;

}
-->
</script>
</head>
<body>
<div class="page">
		<div class="header">
			<div>
				<a href="/zeroOut/" id="logo"><img src="../static/images/logo.gif" alt="logo"></a>
				<ul>
					<li>
						<a href="/zeroOut/get_home">首页</a>
					</li>
					<li>
						<a href="/zeroOut/get_my_user_home">个人主页</a>
					</li>
					<li class="selected">
						<a href="/zeroOut/get_my_follow_user">关注</a>
					</li>
					<li >
						<a href="/zeroOut/get_my_fan">粉丝</a>
					</li>
					<li>
						<a href="/zeroOut/display_profile">个人资料</a>
					</li>
					<li>
						<a href="/zeroOut/enter_change_passwd">我的帐号</a>
					</li>
					<li>
						<a href="/zeroOut/explore">随便看看</a>
					</li>
					<li>
						<a href="/zeroOut/">登出</a>
					</li>
				</ul>
			</div>
		</div>
		<div class="body">
			<div>
				<div>
				<ul class="blog">
				
										
				<table width="80%" border="0">
				<tr>
					<td>
					<p>&nbsp;&nbsp;我的关注：</p>
					{%if follow_users%}
					<table id="block" style="margin-top:25px">
                    <tr>
                    <th> Name </th>
                    <th> Delete </th>
                    <th> Homepage </th>
                    </tr>
					{%for follow in follow_users%}
					    <tr>
						<td>{{ follow.name }}</td>
                        <td>
							<form name="removeFollowForm" action = "{% url 'zeroOut:delete_follow_user' %}" method="post">
                            {% csrf_token %}
							<p>
								<input type="hidden" name="followuid" value={{follow.uid}}>
								&nbsp;&nbsp;&nbsp;&nbsp;
								<input type="submit" name="removeFollowUser" value="移除关注"/>
							</p>
						    </form>
                        </td>
                    <td>
						<form name="FollowersHomepageForm" action="{% url 'zeroOut:get_other_user_home' %}" method="post">
                        {% csrf_token %}
						<p>
						<input type="hidden" name="uid" value={{follow.uid}}> 
						&nbsp;&nbsp;&nbsp;&nbsp;
                        <input type="submit" name="homepage" value="ta的主页"/>
						</p>
						</form>
                    </td>
					    </tr>
                    {% endfor %}
                    </table>
                    {% else %}
                    <p>No followers are available.</p>
                    {% endif %}
					</td>
					</tr>
					</table>
					</ul>
				</div>
			</div>
		</div>
		
		<div class="footer">
			<div>
				<ul>
					<li>
						<a href="/zeroOut/">登录</a>
					</li>
					<li>
						<a href="/zeroOut/register">注册</a>
					</li>
					<li>
						<a href="/zeroOut/about">关于</a>
					</li>
				</ul>
				
				<div class="connect">
					<a href="#" id="sina">weibo</a>
					<a href="#" id="facebook">facebook</a>
					<a href="#" id="twitter">twitter</a>
				</div>
				<p class="footnote">&#169; Copyright &#169; 2019. ZeroOut Group. All rights reserved</p>
				<p class="footnote"> SNS Website Using gStore System, Peking University</p>
			</div>
		</div>
	</div>
</body>
</html>

web/templates/login.html
<!DOCTYPE html>

<html>
<head>
	<meta charset="UTF-8">
	<title>ZeroOut登录</title>
	<link rel="stylesheet" href="../static/css/style.css" type="text/css">

<script language="javascript">
function check(form){
	if (form.username.value==""){
		alert("请输入用户名称!");form.name.focus();return false;
	}
	if (form.password.value==""){
		alert("请输入密码!");form.pwd.focus();return false;
	}
}
function check1(){
	if (1){
		alert("请输入用户名称!");return false;
	}
	if (0){
		alert("请输入密码!");return false;
	}
}
</script>
</head>
<body>

	<div class="page">
		<div class="header">
			<div>
				<a href="/zeroOut/" id="logo"><img src="../static/images/logo.gif" alt="logo"></a>
				<ul>
					<li class="selected">
						<a href="/zeroOut/">登录</a>
					</li>
					<li>
						<a href="/zeroOut/register">注册</a>
					</li>
					<li>
						<a href="/zeroOut/about">关于</a>
					</li>
				</ul>
			</div>
		</div>
		<div class="body">
			<div>
				<div id="featured">
					<h3>ZeroOut Social</h3>
					<form name="loginForm" action="{% url 'zeroOut:login' %}" method="post">
                    {% csrf_token %}
						<table width="100%" border="0" cellpadding="0" cellspacing="0"
							bordercolorlight="#FFFFFF" bordercolordark="#D2E3E6">
							<tr>
								<td height="57">&nbsp;</td>
								<td height="57" colspan="2" align="left">&nbsp;</td>
								<td>&nbsp;</td>
							</tr>
							<tr>
							<td width="10%">&nbsp;</td>
							</tr>
						
							<tr>
								<td width="10%" height="40%"><p>用户名：&nbsp;&nbsp;
									<input name="name" type="text" id="username" size="28" height="20%"></p></td>
								<td width="9%">&nbsp;</td>
							</tr>
							<tr>
								<td width="10%" height="40%">&nbsp;</td>
							</tr>
							<tr>
								<td><p>&nbsp;&nbsp;密码：&nbsp;&nbsp;&nbsp;&nbsp; 
									<input name="pwd" type="password" id="password" size="29" height="20%"></p>
								</td>
								<td width="9%">&nbsp;</td>
							</tr>
						
						</table>
								<a><input name="resetBtn" type="reset" value="重置" size="25" height="25">&nbsp;&nbsp;
									<input  align="right" name="submitBtn" type="submit" value="登录" onClick="return check(loginForm)" size="25"> &nbsp; 
								</a>
					</form>
			  </div>
			</div>
			<div>
				<ul class="blog">
					<li>
						<a href="/zeroOut/about"><img src="../static/images/glove.png" alt=""></a>
						<h3>ZeroOut是基于gStore图数据库系统的社交网络</h3>
						<p>ZeroOut Social is a social network website based on gStore System.</p>
					</li>
					<li>
						<a href="/zeroOut/about"><img src="../static/images/baseball.png" alt=""></a>
						<h3>ZeroOut是基于gStore图数据库系统的社交网络</h3>
						<p>You can post microblog after you log in.</p>
					</li>
					<li>
						<a href="/zeroOut/about"><img src="../static/images/bat.png" alt=""></a>
						<h3>ZeroOut是基于gStore图数据库系统的社交网络</h3>
						<p>You can follow other people to find out what they are talking about and feeling.</p>
					</li>
				</ul>
			</div>
		</div>
		<div class="footer">
			<div>
				<ul>
					<li>
						<a href="/zeroOut/">登录</a>
					</li>
					<li>
						<a href="/zeroOut/register">注册</a>
					</li>
					<li>
						<a href="/zeroOut/about">关于</a>
					</li>
				</ul>
				<p>ZeroOut Social is a social network website based on gStore System. You can post microblog after you log in. You can also follow other people to find out what they are talking about and feeling.</p>
				<div class="connect">
					<a href="#" id="sina">weibo</a>
					<a href="#" id="facebook">facebook</a>
					<a href="#" id="twitter">twitter</a>
				</div>
				<p class="footnote">&#169; Copyright &#169; 2019. ZeroOut Group. All rights reserved</p>
				<p class="footnote"> SNS Website Using gStore System, Peking University</p>
			</div>
		</div>
	</div>
</body>
</html>

web/templates/usermain.html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>我的首页
    </title>
	<link rel="stylesheet" href="../static/css/style.css" type="text/css">
		<script>
<!--
function checkLength(textarea)
{
	if (textarea.value.length > 140)
		{	
			alert("输入的新鲜事太长啦");
			textarea.focus();
			return false;
		}
			if (textarea.value.length == 0)
		{	
			alert("没输入新鲜事呢");
			textarea.focus();
			return false;
		}
}
function clickText(textarea)
{	
	textarea.focus();
}
-->
</script>
<title>我的首页</title>

</head>
<body>
<div class="page">
		<div class="header">
			<div>
				<a href="/zeroOut/" id="logo"><img src="../static/images/logo.gif" alt="logo"></a>
				<ul>
					<li class="selected">
						<a href="/zeroOut/get_home">首页</a>
					</li>
					<li>
						<a href="/zeroOut/get_my_user_home">个人主页</a>
					</li>
					<li>
						<a href="/zeroOut/get_my_follow_user">关注</a>
					</li>
					<li>
						<a href="/zeroOut/get_my_fan">粉丝</a>
					</li>
					<li>
						<a href="/zeroOut/display_profile">个人资料</a>
					</li>
					<li>
						<a href="/zeroOut/enter_change_passwd">我的帐号</a>
					</li>
					<li>
						<a href="/zeroOut/explore">随便看看</a>
					</li>
					<li>
						<a href="/zeroOut/">登出</a>
					</li>
				</ul>
			</div>
		</div>
		
		<div class="body">
			<div>
			<form name="form1" action="{% url 'zeroOut:send_weibo' %}" method="post">	
            {% csrf_token %}
				<div>
				<ul class="blog">							
						<table width="80%" border="0">
						 <tr>
							<td>
								<textarea name="my_news" id="my_news" rows="10" cols="60" onClick="return clickText(this)"></textarea>
							</td>
							<td>
                                <p><a href="#">微博</a> {{ weibo_num }} &nbsp; &nbsp; &nbsp;</p>
                                <p><a href="/zeroOut/get_my_follow_user">关注</a> {{ follow_num }} &nbsp; &nbsp; &nbsp;</p>
                                <p><a href="/zeroOut/get_my_fan">粉丝</a> {{ fan_num }}&nbsp; &nbsp; &nbsp;</p>
							</td>
						 </tr>
						 <tr>
							<td align="center"><input name="release" type="submit" value="发布" onClick="return checkLength(my_news)">&nbsp; 
							<input name="clear" type="reset" value="清空" onClick="return clickText(my_news)"></td>
						</tr>
						</table>
					</ul>

					<ul>
                    <p>好友们的新鲜事</p>

                    {%if weibos%}
                    {%for weibo in weibos%}
                    <p> -------------------------------------------------------------------------------------------- </p>
                    <p> {{weibo.weibo_uid_name}} </p>
                    <p> {{weibo.weibo_date}} </p>
                    <p> {{weibo.weibo_text}} </p>
                    <p> 转发：{{weibo.weibo_repostsnum}}
                    评论：{{weibo.weibo_commentsnum}}
                    点赞：{{weibo.weibo_attitudesnum}} </p>
                    {% endfor %}
                    
                    {% else %}
                    <p> No weibos are available.</p>
                    {% endif %}
					</ul>
				</div>
		</form>
			</div>
		</div>		
		<div class="footer">
			<div>
				<ul>
					<li>
						<a href="/zeroOut/">登录</a>
					</li>
					<li>
						<a href="/zeroOut/register">注册</a>
					</li>
					<li>
						<a href="/zeroOut/about">关于</a>
					</li>
				</ul>
				
				<div class="connect">
					<a href="#" id="sina">weibo</a>
					<a href="#" id="facebook">facebook</a>
					<a href="#" id="twitter">twitter</a>
				</div>
				<p class="footnote">&#169; Copyright &#169; 2019. ZeroOut Group. All rights reserved</p>
				<p class="footnote"> SNS Website Using gStore System, Peking University</p>
			</div>
		</div>
	</div>
</body>
</html>